version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: manuallyDatabase
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SenhaForte123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: